api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        json: ['application/json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
