framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'hello@mail.donneargent.com'
        headers:
            From: 'DonneArgent <hello@mail.donneargent.com>'
