name: Push & deploy docker image to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push api image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:api"
          push: true
          tags: mides/challenge-s1-api-platform:latest

      - name: Build and push front image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:front"
          push: true
          tags: mides/challenge-s1-front:latest
